export const ALERT_CATEGORIAS = {
  MANUTENCAO: 'MANUTENCAO',
  RECOMENDACAO: 'RECOMENDACAO',
  SEGURO: 'SEGURO',
  CONTRATO: 'CONTRATO',
  OS_CORRETIVA: 'OS_CORRETIVA',
};

export const ALERT_EVENTOS = {
  MANUT_PROX_INICIO: 'MANUT_PROX_INICIO',
  MANUT_INICIADA: 'MANUT_INICIADA',
  MANUT_PROX_FIM: 'MANUT_PROX_FIM',
  MANUT_CONFIRMACAO: 'MANUT_CONFIRMACAO',

  RECOM_PREVENTIVA: 'RECOM_PREVENTIVA',

  SEGURO_VENCE: 'SEGURO_VENCE',
  SEGURO_VENCIDO: 'SEGURO_VENCIDO',

  CONTRATO_VENCE: 'CONTRATO_VENCE',
  CONTRATO_VENCIDO: 'CONTRATO_VENCIDO',

  OS_CORRETIVA_VISITA_VENCIDA: 'OS_CORRETIVA_VISITA_VENCIDA',
};

export const ALERT_PRIORIDADES = {
  BAIXA: 'Baixa',
  MEDIA: 'Media',
  ALTA: 'Alta',
};

export function getAlertTypeLabel(categoria) {
  if (categoria === ALERT_CATEGORIAS.RECOMENDACAO) {
    return 'Recomendação';
  }

  return 'Alerta';
}
