export const ALERT_CATEGORIAS = {
  MANUTENCAO: 'MANUTENCAO',
  RECOMENDACAO: 'RECOMENDACAO',
  SEGURO: 'SEGURO',
  CONTRATO: 'CONTRATO',
};

export const ALERT_EVENTOS = {
  MANUT_PROX_INICIO: 'MANUT_PROX_INICIO',
  MANUT_INICIADA: 'MANUT_INICIADA',
  MANUT_PROX_FIM: 'MANUT_PROX_FIM',
  MANUT_CONFIRMACAO: 'MANUT_CONFIRMACAO',

  RECOM_PREVENTIVA: 'RECOM_PREVENTIVA',

  SEGURO_VENCE: 'SEGURO_VENCE',
  SEGURO_VENCIDO: 'SEGURO_VENCIDO',

  CONTRATO_VENCE: 'CONTRATO_VENCE',
  CONTRATO_VENCIDO: 'CONTRATO_VENCIDO',
};

// 🔥 PRIORIDADE TÉCNICA (ordenável)
export const ALERT_PRIORIDADES = {
  BAIXA: 1,
  MEDIA: 2,
  ALTA: 3,
};

// 🔥 LABELS (para UI)
export const ALERT_PRIORIDADE_LABEL = {
  1: 'Baixa',
  2: 'Média',
  3: 'Alta',
};